### ISSUE TITLE
🎄 Presents for end of year cycle [Summary Issue]

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1486]
We want to start fresh next year so this is a lose bucket list for the rest of the year:

- [x] Remove Storybook Docs -> use regular TS(X) (https://storybook.js.org/docs/react/api/csf)
- [x] Re-fit the ordering of how styles are applied: #1494
- [x] Merge Box and Element: #1550
- [x] Remove all `useStyles` and delete related packages: #1395 
- [x] add GlobalStyles: #1395 
- [x] Icons site and search (with copy-pasta for the SVG code): #1520 
- [x] Refactor layout components
	- [x] Column/Columns: #1035 
	- [x] Stack: #1510 
	- [x] Inline: #1511 
- [x] Cleanup Themes and Theme structure 
	- [x] #996
	- [x] check all component variants (if they are correct, better naming, etc.) --> last of this is handled in #1570, #1571, #1638

**Comment by ti10le** [comment]
What do you mean exactly with icons site and search? .. copy-pasta sounds tasty ☺️

**Comment by sebald** [comment]
@ti10le the request from @julianthiel about a searchable page for icons where you can copy the svg code (for usage outside marigold)

**Comment by ti10le** [comment]
@sebald can we collect the points within:  Cleanup Themes and Theme structure
Whats all included in this point? How can theme-ui help us with this issue?

**Comment by ti10le** [comment]
Last missing is to rewrite the component stories to .tsx
Then we can check if #1226 and #1255 is also done with this work.
