### ISSUE TITLE
Roadmap to version 0.1

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#194]
# Roadmap

**Disclaimer: This issue is used to track what required to release a minimal usable version of `marigold`. We'll add/remove items along the way. This is used for an ETA.**

---

## Components

- **Typography**
	- [x] Text
	- [x] Heading
	- [x] Link
- **Form**
	- [x] Button
	- [x] Label
	- [x] Input
	- [x] Textarea
	- [x] Select
	- [x] Checkbox (maybe: https://reacttraining.com/reach-ui/checkbox)
	- [x] Radio
	- [x] Slider (based on: https://reacttraining.com/reach-ui/slider)
	- [x] Field (Label + Input/... + Message)
- **Content**
	- [x] Message
	- [x] Alert (based on: https://reacttraining.com/reach-ui/alert)
	- [x] Image
	- [x] Badge
	- [x] Dialog (based on: https://reacttraining.com/reach-ui/dialog)
	- [x] Menu (based on: https://reacttraining.com/reach-ui/menu-button)
	- [x] Validation Message
- **Layout**
	- [x] Container ("Box" is already used)
	- [x] Stack
	- [x] Column
 	- [x] Columns
	- [x] Hidden
	- [x] Divider
- **Iconography**
	- [x] SVG
	- [x] Icon
	- [x] `@marigold/icons` package that host our icons

## Misc

- [x] Storybook
- [x] Testing
- [x] Publish

**Comment by sebald** [comment]
Maybe we can make use of https://react-spectrum.adobe.com/ to improve our accessibility

**Comment by sebald** [comment]
@viktoria-schwarz @ti10le Uh one checkbox missing?! :D
