### ISSUE TITLE
Use a common base for all themes

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#2002]
## Description

It is obnoxious to use stuff like `grey40` and make sure it is used for every border and stuff like this. We need a more semantic design tokens!

**Tasks:**

- [ ] Update `createTheme` with semantic colors
- [ ] Update `b2b-theme` (use `createTheme`)
- [ ] Update `core-theme` (use `createTheme`)
- [ ] Update `unicorn-theme` (use `createTheme`)
- [ ] Update `docs-theme` (use `createTheme`)

**Semantic Colors:**

- colors
    - text
    - background
    - primary
    - secondary
    - disabled
    - error
    - warning
    - info
    - success
- fonts
    - body
    - heading

## Context

We already started the work with `@margiold/create-theme` we need to add some more features and make it more usable.

## Consequences

Helps maintain a common base for theme with sensible defaults.

**Comment by sebald** [comment]
Do #2153 before this?

**Comment by sebald** [comment]
I don't think this is a good idea anymore. We tried this for the docs and it makes it much harder to look up available tokens 😐

**Comment by benediktgrether** [comment]
- [ ] Check colors of the components.
- [ ] Define how semantic colors can be used.
