### ISSUE TITLE
Refa: <Table>

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#2019]
The following things should be improved on the `<Table>` component:

- [x] Use `<Checkbox>` #2081
- [x] Switching between a cell with data and a cell with a checkbox should not be decided in the `<TableCell>`. We should rather have two dedicated Cells. #2081
- [x] Keyboard Focus is always shown #2081
- [x] Remove `align` props, this can be done via styling #2036 
- [x] ~~Make the cell with the checkbox a separate part for styling?~~
- [x] Is cell spacing correct? #2081
- [x] Make [nested columns](https://react-spectrum.adobe.com/react-spectrum/TableView.html#nested-columns) work #2081
- [x] ~~disabling rows doesn't work~~ works ... `react-aria` documentation isn't correct :D
- [x] #2107
