### ISSUE TITLE
Marigold Core StartPage

### ISSUE THREAD

**Issue by sarahgm** [marigold-ui/marigold#2559]
**Core Startpage**

**Infos:**
has two major functionalities:
1. favourites as cards (as "Mitarbeiter" you see always the master 1.  as card)
2. tree structure (Lists) -> possibility to choose your favs, if fav than add star icon to Card

Note: json is generated from each php model so you simple have all necessary data (name etc.)

**TO-DOs:**
- [x] checkout react branch from core -> new branch
- [x] get access to all possible scenarios (Master + Favs + List)
- [x] improve core theme from Marigold with styles (especially Card component + not filled star icon) #2551 #2564 
- [x] get all data from php

**Open Questions to @sebald :**
- ~structure of tsx files and the js files (are they generated?)~

**Comment by sebald** [comment]
@sarahgm what do you mean by generated? 🤔 

The react branch has a "starter template" you can copy. I can show you tomorrow ☺️
