### ISSUE TITLE
Roadmap to Marigold Docs Page

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#743]
# Roadmap to Marigold Docs Page 
![image](https://user-images.githubusercontent.com/59875255/111283247-35497400-863f-11eb-969d-a1f752833241.png)

**Disclaimer: This issue is used to track what required to release a documentation page of `marigold`. We'll add/remove items along the way.
Motto: "Good planning saves a lot of programming work"**

---
Info Pages:
- [Marigold on Confluence](https://confluence.rsvx.it/display/DESIGN/Marigold)
- [B2B Menu example](https://www.figma.com/file/Jc0TeCwH6n4FUXQLDGqR39Ky/B2B-Design-System---Components?node-id=0%3A13)
- [Menu example on Confluence](https://confluence.rsvx.it/display/DESIGN/Menus)
---
Workflow:
- make your changes in a separate branch and push commits as PR to main
- merge into main
- if we have enough changes to publish a new version then push from main the docs to the gh-pages branch
- deploy means to release a npm marigold version **and** a new version of docs page
---
- **Infrastructure**
	- [x] create [gh-pages](https://github.com/marigold-ui/marigold/settings) branch
	- [x] [create github-page](https://pages.github.com/) from the gh-pages branch -> click project site and then start from scratch
	- [x] [Discussion](https://github.com/marigold-ui/marigold/discussions/749) --> create docs folder as own workspace on repo root level
- **Docs Page Content**
	- [x] use content structure from Marigold on Confluence and create a basic Navigation (rough structure see the image below)
	- [x] create template/structure for displaying a component #925 
	- [ ] Fill the content structure
		- [x] add markdown **Component** pages #939 
		- [ ] add markdown **Design Tokens** pages #940
		- [ ] add and create markdown **Design Language** pages (needs content from UX/UI)
	- [ ] add additional content to better component description. Infos from Confluence or Toshi
	- [ ] add minimum one more functional theme to the gatsby site and make possibly to change between them (e.g. b2b and unicorn)
	- [ ] complete missing designs
	- [x] add the missing components from Roadmap to 0.1 #194
	- [ ] add missing components from our Issues
- **Clean-up Repo**
	- [ ] remove storybook docs from config
	- [ ] remove storybook docs from components
- **Work after first Version**
	- [ ] prepare presentation/talk about Marigold for all interested people
	- [ ] publish link in slack, per mail, ..

**Comment by ti10le** [comment]
![8392BFB6-8F01-400C-8AAF-BBE792187740_1_201_a](https://user-images.githubusercontent.com/59875255/106880359-8aa77280-66dc-11eb-85b7-ecefa7c2de7d.jpeg)

**Comment by sebald** [comment]
@ti10le do we still need this?

**Comment by ti10le** [comment]
I think we dont need this anymore.
