### ISSUE TITLE
Storybook: New Structure with more focus on development

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#926]
## Description
Until now we used Storybook as a canvas for our development and as a documentation page for the components.

As we move the documentation to our Gatsby site, we want to exclusively focus on the development part and our components in Storybook.

We want to see all variants at once (per component), the source code, functionalities and prop table.

## Problems
* Storybook Tabs as we have them now are not convenient for a good overview of all variants and combinations of a component
* We need new plugins that allow us to see the source code (usage), the functionalities of a component, the prop table with little code-wise effort
* focus on the components in storybook and don't mix it with documentation!

## Todos

- [x] instead of "Canvas" and "Docs" as tabs, use a Default in storybook and the Variants as subpages of each component, so that on click of a component name in the sidebar navigation menu, the component shows up with *all* its variants
- [x] we can use [Knobs addon](https://storybook.js.org/addons/@storybook/addon-knobs/) to edit/test props and values dynamically
- [x] maybe use Doc [blocks addon](https://storybook.js.org/docs/react/writing-docs/doc-blocks) to automatically create props table
- [x] delete "How to write components" section

## Consequences
We have a clean storybook with all our components that helps us testing and seeing our component library with different themes. Documentation is excluded from this.

**Comment by viktoria-schwarz** [comment]
- Knobs addon is deprecated --> use [Controls addon](https://storybook.js.org/addons/@storybook/addon-controls)
- ArgsTable can be generated but values need to be specified in the Component.stories.mdx file 
- one or two Tabs??

**Comment by viktoria-schwarz** [comment]
- added "Welcome" story with very short explanation and links
- added useStyles hook story (for completeness as it is important for developers)
- I would stick with 2 tabs, Canvas and Docs: Canvas shows a single component with addon tabs (Accessibility, Controls, Actions --> testing) and Docs shows the (self-generated) Args Table where you can play around with the input values
